services:
  dev-db:
    image: postgres:16
    ports:
      - "5332:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs-pug-app
    networks:
      - db

networks:
  db:
    driver: bridge